language: java
sudo: false

jdk:
  - openjdk8

env:
  - TERM=dumb

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew bintrayUpload

branches:
  only:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
